/**
 * Curated Ionicons names for address icon picker.
 * All names are valid Ionicons (outline variants preferred for consistency).
 */
export const ADDRESS_ICONS: string[] = [
  // Home & Living
  "home-outline",
  "business-outline",
  "bed-outline",
  "tv-outline",
  "key-outline",
  "bulb-outline",
  "water-outline",
  "flame-outline",
  "construct-outline",
  "hammer-outline",
  "color-palette-outline",

  // People
  "person-outline",
  "people-outline",
  "woman-outline",
  "man-outline",
  "body-outline",
  "walk-outline",
  "happy-outline",
  "heart-outline",
  "heart-half-outline",
  "accessibility-outline",
  "hand-left-outline",
  "hand-right-outline",

  // Transportation
  "car-outline",
  "car-sport-outline",
  "bus-outline",
  "airplane-outline",
  "train-outline",
  "boat-outline",
  "bicycle-outline",
  "navigate-outline",
  "compass-outline",
  "map-outline",
  "location-outline",
  "pin-outline",
  "rocket-outline",
  "speedometer-outline",

  // Food & Drink
  "restaurant-outline",
  "cafe-outline",
  "wine-outline",
  "beer-outline",
  "pizza-outline",
  "fast-food-outline",
  "ice-cream-outline",
  "nutrition-outline",
  "basket-outline",
  "cart-outline",
  "storefront-outline",

  // Education & Work
  "school-outline",
  "book-outline",
  "library-outline",
  "newspaper-outline",
  "document-outline",
  "briefcase-outline",
  "desktop-outline",
  "laptop-outline",
  "calculator-outline",
  "clipboard-outline",
  "pencil-outline",
  "create-outline",
  "archive-outline",

  // Health & Fitness
  "medkit-outline",
  "fitness-outline",
  "barbell-outline",
  "bandage-outline",
  "pulse-outline",
  "thermometer-outline",
  "flask-outline",
  "eyedrop-outline",

  // Nature & Outdoors
  "leaf-outline",
  "flower-outline",
  "earth-outline",
  "globe-outline",
  "sunny-outline",
  "partly-sunny-outline",
  "rainy-outline",
  "snow-outline",
  "thunderstorm-outline",
  "cloudy-outline",
  "paw-outline",
  "fish-outline",
  "bug-outline",

  // Entertainment & Sports
  "musical-notes-outline",
  "headset-outline",
  "game-controller-outline",
  "football-outline",
  "basketball-outline",
  "baseball-outline",
  "tennisball-outline",
  "golf-outline",
  "dice-outline",
  "trophy-outline",
  "film-outline",
  "ticket-outline",
  "mic-outline",
  "radio-outline",

  // Shopping & Finance
  "bag-outline",
  "pricetag-outline",
  "gift-outline",
  "card-outline",
  "cash-outline",
  "wallet-outline",
  "cut-outline",
  "shirt-outline",
  "watch-outline",
  "diamond-outline",

  // Communication & Tech
  "call-outline",
  "mail-outline",
  "chatbubble-outline",
  "camera-outline",
  "phone-portrait-outline",
  "wifi-outline",
  "bluetooth-outline",
  "print-outline",
  "share-outline",
  "cloud-outline",
  "qr-code-outline",

  // Symbols & Misc
  "bookmark-outline",
  "flag-outline",
  "star-outline",
  "shield-outline",
  "lock-outline",
  "alarm-outline",
  "time-outline",
  "calendar-outline",
  "ribbon-outline",
  "medal-outline",
  "telescope-outline",
  "planet-outline",
  "moon-outline",
  "glasses-outline",
  "umbrella-outline",
  "hourglass-outline",
  "infinite-outline",
];
