#!/usr/bin/env node
/**
 * sync-shared.mjs
 *
 * Mirrors the canonical `_shared/` directory (here, in the mobile
 * repo) into the other Gaznger repos that consume it. Since the three
 * repos live separately on disk, we copy by file path rather than
 * via a workspace package.
 *
 * Run from the mobile repo root:
 *
 *     node scripts/sync-shared.mjs
 *
 * Behaviour:
 *   1. Walk `_shared/`, copy every file to each destination at the
 *      same relative path.
 *   2. Add a "DO NOT EDIT" header to every copied file (the mobile
 *      copy stays editable; the destinations are read-only mirrors).
 *   3. Warn if the destination has files the source doesn't (someone
 *      hand-edited the mirror — drift).
 *
 * Destinations are computed relative to this repo's location. If the
 * server / admin-web repos live elsewhere on your machine, set
 * `GAZNGER_SERVER_PATH` / `GAZNGER_ADMIN_PATH` env vars.
 */

import { readdir, readFile, writeFile, mkdir, stat } from "node:fs/promises";
import { existsSync } from "node:fs";
import { join, relative, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const MOBILE_ROOT = join(__dirname, "..");
const SOURCE = join(MOBILE_ROOT, "_shared");

// Default destination paths assume the standard layout:
//   <Gaznger_app>/mobile/gaznger/_shared      (canonical)
//   <Gaznger_app>/server/src/_shared          (mirror)
//   <Gaznger_app>/admin-web/src/_shared       (mirror, when adopted)
const APP_ROOT = join(MOBILE_ROOT, "..", "..");
const DESTS = [
  {
    name: "server",
    path:
      process.env.GAZNGER_SERVER_PATH ??
      join(APP_ROOT, "server", "src", "_shared"),
  },
  {
    name: "admin-web",
    path:
      process.env.GAZNGER_ADMIN_PATH ??
      join(APP_ROOT, "admin-web", "src", "_shared"),
  },
];

const HEADER = `/**
 * ⚠️  AUTO-GENERATED FROM mobile/gaznger/_shared/  ⚠️
 *
 * Do NOT edit this file directly — your changes will be overwritten
 * the next time someone runs \`scripts/sync-shared.mjs\` from the
 * mobile repo. Edit the canonical copy in mobile/gaznger/_shared/
 * instead, then re-run the sync.
 */

`;

async function walk(dir, files = []) {
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) await walk(full, files);
    else files.push(full);
  }
  return files;
}

async function copyFile(src, destFile) {
  const content = await readFile(src, "utf8");
  const isCode = /\.(ts|js|mjs)$/.test(src);
  // Don't double-prepend if we're re-syncing into a destination that
  // already has the header.
  const hasHeader = content.startsWith("/**\n * ⚠️");
  const out =
    isCode && !hasHeader ? HEADER + content : isCode && hasHeader ? content : content;

  await mkdir(dirname(destFile), { recursive: true });
  await writeFile(destFile, out, "utf8");
}

async function syncTo(dest) {
  if (!existsSync(dirname(dest.path))) {
    console.log(`  [skip] ${dest.name} — parent directory not found at ${dirname(dest.path)}`);
    return;
  }

  await mkdir(dest.path, { recursive: true });

  const sourceFiles = await walk(SOURCE);
  let copied = 0;
  for (const src of sourceFiles) {
    const rel = relative(SOURCE, src);
    const destFile = join(dest.path, rel);
    await copyFile(src, destFile);
    copied++;
  }

  // Drift check: any files in the destination that aren't in source?
  const destFiles = existsSync(dest.path) ? await walk(dest.path) : [];
  const sourceRels = new Set(sourceFiles.map((f) => relative(SOURCE, f)));
  const orphans = destFiles
    .map((f) => relative(dest.path, f))
    .filter((r) => !sourceRels.has(r));

  console.log(`  [ok]   ${dest.name} — ${copied} files synced to ${dest.path}`);
  if (orphans.length > 0) {
    console.log(`         ⚠️  ${orphans.length} orphan file(s) in destination (not in source):`);
    orphans.forEach((o) => console.log(`           - ${o}`));
    console.log(`         Either delete them or move them into the canonical _shared/.`);
  }
}

(async () => {
  const sourceExists = existsSync(SOURCE);
  if (!sourceExists) {
    console.error(`✗ source ${SOURCE} not found.`);
    process.exit(1);
  }

  console.log(`syncing _shared/ from mobile/gaznger →`);
  for (const dest of DESTS) {
    await syncTo(dest);
  }
  console.log(`done.`);
})();
